{% set version = "1.10.2" %}

package:
  name: dyff
  version: {{ version }}

source:
  url: https://github.com/homeport/dyff/archive/v{{ version }}.tar.gz
  sha256: 36e103c1424e79135bb4ed54d6b66e6c3f057ff422a5838d3a80ffd4d9a3ef27

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - dyff version

about:
  home: https://github.com/homeport/dyff
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A diff tool for YAML files, and sometimes JSON
  doc_url: https://github.com/homeport/dyff
  dev_url: https://github.com/homeport/dyff

extra:
  recipe-maintainers:
    - danielnachun
    - asford
