schema_version: 1

context:
  version: "1.10.4"

package:
  name: dyff
  version: ${{ version }}

source:
  url: https://github.com/homeport/dyff/archive/v${{ version }}.tar.gz
  sha256: eb0df6175ff66cc3494c856c2d70b980811bf3202b71be444209951458427ebf

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - dyff version

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A diff tool for YAML files, and sometimes JSON
  homepage: https://github.com/homeport/dyff
  repository: https://github.com/homeport/dyff
  documentation: https://github.com/homeport/dyff

extra:
  recipe-maintainers:
    - danielnachun
    - asford
