schema_version: 1

context:
  version: "1.11.0"

package:
  name: dyff
  version: ${{ version }}

source:
  url: https://github.com/homeport/dyff/archive/v${{ version }}.tar.gz
  sha256: 30f8bf96acbc4a4c0b0dc857e849ca8903cf5311bb7e96cdaf2cf2d4d137be44

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - dyff version

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A diff tool for YAML files, and sometimes JSON
  homepage: https://github.com/homeport/dyff
  repository: https://github.com/homeport/dyff
  documentation: https://github.com/homeport/dyff

extra:
  recipe-maintainers:
    - danielnachun
    - asford
