schema_version: 1

context:
  version: "1.12.0"

package:
  name: dyff
  version: ${{ version }}

source:
  url: https://github.com/homeport/dyff/archive/v${{ version }}.tar.gz
  sha256: 3edeb78b3166fc7ba4cdea1c9339eacbd57d768f27a77564adf58dc8819df75f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - dyff version

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A diff tool for YAML files, and sometimes JSON
  homepage: https://github.com/homeport/dyff
  repository: https://github.com/homeport/dyff
  documentation: https://github.com/homeport/dyff

extra:
  recipe-maintainers:
    - danielnachun
    - asford
